In [1]:
import pandas as pd,numpy as np

In [4]:
df1=pd.DataFrame({'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}})
df1

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [5]:
pd.DataFrame({'Ohio':df1['Ohio'][:-1],'Nevada':df1['Nevada'][:2]})

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [6]:
df1.index.name='year'
df1.columns.name='state'
df1

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [7]:
df1.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [8]:
df1["Nevada"].unique()

array([ nan,  2.4,  2.9])

In [10]:
df1['Ohio'].unique()

array([ 1.5,  1.7,  3.6])

In [11]:
df1.reindex([2000,2002,2001,2003],fill_value=0)# 调用reindex将会根据新索引进行重排。如果某个索引值当前不存在，就引入缺失值

state  Nevada  Ohio
year               
2000      NaN   1.5
2002      2.9   3.6
2001      2.4   1.7
2003      0.0   0.0

In [14]:
df=pd.DataFrame(np.arange(9).reshape(3,3),index=["a","c","d"],columns=["haha","heihei","hehe"])
df

haha  heihei  hehe
a     0       1     2
c     3       4     5
d     6       7     8

In [21]:
df.reindex(["a","b","c","d"],method='ffill')# method='ffill',method='bfill'

haha  heihei  hehe
a     0       1     2
b     0       1     2
c     3       4     5
d     6       7     8

In [28]:
df.loc[["a","d"]]

haha  heihei  hehe
a     0       1     2
d     6       7     8

In [33]:
df1=df['haha'].apply(lambda x:x**8)

In [34]:
df['haha1']=df1
df

haha  heihei  hehe    haha1
a     0       1     2        0
c     3       4     5     6561
d     6       7     8  1679616

In [97]:
df=pd.DataFrame({'a':{0:"c3h4o5",1:"ch2o3"},"b":{0:"c6h12o2",1:"c5h10o12"}})
df

a         b
0  c3h4o5   c6h12o2
1   ch2o3  c5h10o12

In [100]:
import re
def c_value(m):
    value=re.findall(r'c(\d+)',m)
    if len(value)==0:
        return 1
    return value[0]

def h_value(m):
    value=re.findall(r'h(\d+)',m)
    if len(value)==0:
        return 1
    return value[0]
for i in (["a","b"]):
    df["H_%s"%i]=df[i].apply(h_value)
    df['C_%s'%i]=df[i].apply(c_value)
df

a         b H_a C_a H_b C_b
0  c3h4o5   c6h12o2   4   3  12   6
1   ch2o3  c5h10o12   2   1  10   5